FROM elixir:1.11-alpine

RUN apk add --no-cache --no-progress postgresql-client build-base git tzdata nodejs npm

WORKDIR /app/assets

COPY package.json package-lock.json ./

RUN npm install && node node_modules/webpack/bin/webpack.js --mode development

WORKDIR /app

COPY . ./

RUN mix do local.hex --force, local.rebar --force && mix deps.get

EXPOSE 4000
CMD mix phx.server
